### ISSUE TITLE
Spherical dipolar weights - [merged]

### ISSUE THREAD

**Issue by hejamu** [maicos-devel/maicos#363]
In GitLab by @PicoCentauri on Jun 7, 2023, 09:15 UTC

_Merges spherical_dipolar_weights -> main_

Allow weighting for dipolar order parameters in cylindrical geometry. ~~Still the np.dot has to be fixed to work with 
arrays of shape `(n_atoms, 3) x (3)` and `(n_atoms, 3)` x `(n_atoms, 3)`.~~

# TODO

- [x] Create modules `dipordercylinder`, `dipordersphere`
- [x] Tests for functions and classes
- [x] Documentation for functions and classes

*Migrated from GitLab: https://gitlab.com/maicos-devel/maicos/-/merge_requests/259*

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Jun 7, 2023, 09:16 UTC

added 1 commit

<ul><li>45fa2c2b - draft for cylinder weights</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=701777979&start_sha=4f7bae4e631e2e81d874ccc5761b1befb23847c5)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Jun 7, 2023, 09:30 UTC

added 1 commit

<ul><li>d081d0b5 - draft for cylinder weights</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=701798725&start_sha=45fa2c2b7311580e051ff59cb482372723f18088)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Jun 7, 2023, 10:47 UTC

added 1 commit

<ul><li>bf47c21c - draft for cylinder weights</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=701901063&start_sha=d081d0b512e234b5fef41c8f883e458c00f21fed)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Jun 7, 2023, 10:48 UTC

added 1 commit

<ul><li>95d663d6 - draft for cylinder weights</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=701902958&start_sha=bf47c21c9cf2713c2b302bf1d27a0b704d69ca7d)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Jun 7, 2023, 10:53 UTC

added 1 commit

<ul><li>af8dbc82 - draft for cylinder weights</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=701910149&start_sha=95d663d6fd018dc7404139651b88447c388ad1a0)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Jun 7, 2023, 11:07 UTC

added 1 commit

<ul><li>36c46866 - draft for cylinder weights</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=701928121&start_sha=af8dbc82170c0a3cc54b8d9c3f9238ddbae2eb94)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Jun 7, 2023, 11:13 UTC

added 1 commit

<ul><li>1c8577f9 - draft for cylinder weights</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=701935475&start_sha=36c46866aa374ffdc51d949c1972781892c7780f)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Jun 7, 2023, 11:16 UTC

added 1 commit

<ul><li>357d8ac2 - draft for cylinder weights</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=701938658&start_sha=1c8577f90623af846edcbb45a2a225165d8e0763)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Jun 7, 2023, 11:31 UTC

Commented on [src/maicos/lib/weights.py line 127](https://github.com/maicos-devel/maicos/compare/42b4bafd7301d589437ca3d67f1f377f4495884e..5aa7c24c13dc8b5853b5e1c095b8c83f79bee4b1#diff-4e6c01c477ca908756fcdb4e454535488b989e7d3c60c54ce7648cf39f53195aL127)



I think this line was wrong before. Regardless, which `compound` the user requested the function was always returning the "highest" compound i.e. if the user set `compound="residues"` the function was calculating w.r.t. `molecules`.

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Jun 7, 2023, 14:50 UTC

added 1 commit

<ul><li>b79fb1d9 - Add modules for calculating cylindrical and spherical dipolar order parameters</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=702248416&start_sha=357d8ac236c9dfc00e26d95d0f825e09cfb36a83)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Jun 7, 2023, 15:09 UTC

marked the checklist item **Documentation for functions and classes** as completed

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Jun 7, 2023, 15:09 UTC

added 1 commit

<ul><li>dbe92079 - Add modules for calculating cylindrical and spherical dipolar order parameters</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=702276727&start_sha=b79fb1d9af91ed060a4896f082aa08d7d6bc6a1b)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Jun 7, 2023, 15:09 UTC

marked the checklist item **Documentation for functions and classes** as incomplete

**Comment by hejamu** [comment]
Uff, grave oversight...

**Comment by hejamu** [comment]
resolved all threads

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 25, 2023, 14:03 UTC

Commented on [src/maicos/lib/weights.py line 127](https://github.com/maicos-devel/maicos/compare/42b4bafd7301d589437ca3d67f1f377f4495884e..5aa7c24c13dc8b5853b5e1c095b8c83f79bee4b1#diff-4e6c01c477ca908756fcdb4e454535488b989e7d3c60c54ce7648cf39f53195aL127)



changed this line in version 12 of the diff

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 25, 2023, 14:03 UTC

added 10 commits

<ul><li>5aa7c24c...a451559a - 9 commits from branch <code>main</code></li><li>263e1a02 - Add modules for calculating cylindrical and spherical dipolar order parameters</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=771054423&start_sha=5aa7c24c13dc8b5853b5e1c095b8c83f79bee4b1)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 25, 2023, 14:04 UTC

Commented on [src/maicos/lib/math.py line 634](https://github.com/maicos-devel/maicos/compare/a451559a4bd6daaf686581c3a420fb9356185762..263e1a02db493b8bccf0dba98a4c0e8df3009e96#diff-8e4c65ce4279a1dcda6f1bb64dd81699c1f095096845f164bc6dcd4f5aafe82dR634)



changed this line in [version 13 of the diff](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=771055653&start_sha=263e1a02db493b8bccf0dba98a4c0e8df3009e96#ea753eeef40cf038f80e160d76b66dc02c115f37_634_634)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 25, 2023, 14:29 UTC

added 1 commit

<ul><li>6826e28e - Add modules for calculating cylindrical and spherical dipolar order parameters</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=771084723&start_sha=707d95c7329fae22f9dfcb89ba90791d93be990a)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 25, 2023, 14:32 UTC

added 1 commit

<ul><li>9c70a637 - Remove str for fixed parameters</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=771088081&start_sha=6826e28e99b3e768e8fc4cd0366648f3a20be058)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 28, 2023, 08:17 UTC

added 4 commits

<ul><li>9c70a637...823fad56 - 2 commits from branch <code>main</code></li><li>315e67d9 - Add modules for calculating cylindrical and spherical dipolar order parameters</li><li>245f9d58 - Remove str for fixed parameters</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=771992282&start_sha=9c70a637671acce5713cf888968c26e65cd5406d)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 28, 2023, 11:37 UTC

marked this merge request as **ready**

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 28, 2023, 12:00 UTC

added 1 commit

<ul><li>e66350b9 - linting</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=772241795&start_sha=552c8ed3fe1b4626d993b39a4884ce29ee6d9e33)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 28, 2023, 12:21 UTC

added 1 commit

<ul><li>17f97170 - fix some typehints</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=772265945&start_sha=e66350b955a9a38e411b1b1bd9a24edd5b33861b)

**Comment by hejamu** [comment]
```suggestion:-0+0
        Direction of the cylinder axis (0=x, 1=y, 2=z).
```

**Comment by hejamu** [comment]
```suggestion:-0+0
        Array of the calculated unit vectors with shape (3,) for `pdim='z'` and shape (3,n) for `pdim='r'`. The length of `n` depends on the grouping.
```

**Comment by hejamu** [comment]
`````suggestion:-0+0
        Array of the calculated unit vectors with shape (3,n). The length of `n` depends on the grouping.
```

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 28, 2023, 13:26 UTC

Commented on [src/maicos/lib/util.py line 708](https://github.com/maicos-devel/maicos/compare/823fad56c759519b6c2a99571c1e62e4731c7098..17f97170c493307c1b77a88af165e48163589ed6#diff-0ada1d2edb140a830f51cf314cc8e92d2d2cde24a320fc96c5ca43d6c97b9652R708)



changed this line in [version 20 of the diff](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=772346560&start_sha=17f97170c493307c1b77a88af165e48163589ed6#b3b6ec07b52725dd3cbae6e2ccb9ea06b0bafd43_708_708)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 28, 2023, 13:26 UTC

Commented on [src/maicos/lib/util.py line 732](https://github.com/maicos-devel/maicos/compare/823fad56c759519b6c2a99571c1e62e4731c7098..17f97170c493307c1b77a88af165e48163589ed6#diff-0ada1d2edb140a830f51cf314cc8e92d2d2cde24a320fc96c5ca43d6c97b9652R732)



changed this line in [version 20 of the diff](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=772346560&start_sha=17f97170c493307c1b77a88af165e48163589ed6#b3b6ec07b52725dd3cbae6e2ccb9ea06b0bafd43_732_732)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 28, 2023, 13:26 UTC

Commented on [src/maicos/lib/util.py line 664](https://github.com/maicos-devel/maicos/compare/823fad56c759519b6c2a99571c1e62e4731c7098..17f97170c493307c1b77a88af165e48163589ed6#diff-0ada1d2edb140a830f51cf314cc8e92d2d2cde24a320fc96c5ca43d6c97b9652R664)



changed this line in [version 20 of the diff](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=772346560&start_sha=17f97170c493307c1b77a88af165e48163589ed6#b3b6ec07b52725dd3cbae6e2ccb9ea06b0bafd43_664_664)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 28, 2023, 13:26 UTC

added 1 commit

<ul><li>378a383c - Apply suggestions from code review</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=772346560&start_sha=17f97170c493307c1b77a88af165e48163589ed6)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 28, 2023, 13:36 UTC

Commented on [src/maicos/lib/util.py line 701](https://github.com/maicos-devel/maicos/compare/823fad56c759519b6c2a99571c1e62e4731c7098..378a383ca43c483437a1719fd63b203b414281ee#diff-0ada1d2edb140a830f51cf314cc8e92d2d2cde24a320fc96c5ca43d6c97b9652R701)



Yes, I will fix this!

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 28, 2023, 13:52 UTC

Commented on [src/maicos/lib/util.py line 701](https://github.com/maicos-devel/maicos/compare/823fad56c759519b6c2a99571c1e62e4731c7098..378a383ca43c483437a1719fd63b203b414281ee#diff-0ada1d2edb140a830f51cf314cc8e92d2d2cde24a320fc96c5ca43d6c97b9652R701)



changed this line in [version 21 of the diff](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=772379724&start_sha=378a383ca43c483437a1719fd63b203b414281ee#b3b6ec07b52725dd3cbae6e2ccb9ea06b0bafd43_701_702)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 28, 2023, 13:52 UTC

Commented on [src/maicos/lib/util.py line 711](https://github.com/maicos-devel/maicos/compare/823fad56c759519b6c2a99571c1e62e4731c7098..378a383ca43c483437a1719fd63b203b414281ee#diff-0ada1d2edb140a830f51cf314cc8e92d2d2cde24a320fc96c5ca43d6c97b9652R711)



changed this line in [version 21 of the diff](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=772379724&start_sha=378a383ca43c483437a1719fd63b203b414281ee#b3b6ec07b52725dd3cbae6e2ccb9ea06b0bafd43_711_708)

**Comment by hejamu** [comment]
In GitLab by @PicoCentauri on Aug 28, 2023, 13:52 UTC

added 3 commits

<ul><li>bf512c76 - some typos</li><li>8893d037 - Merge branch &#39;spherical_dipolar_weights&#39; of gitlab.com:maicos-devel/maicos...</li><li>6a46ccf3 - more linting</li></ul>

[Compare with previous version](/maicos-devel/maicos/-/merge_requests/259/diffs?diff_id=772379724&start_sha=378a383ca43c483437a1719fd63b203b414281ee)

**Comment by hejamu** [comment]
approved this merge request

**Comment by hejamu** [comment]
resolved all threads

**Comment by hejamu** [comment]
mentioned in commit db5496e45705e431189058a0892abc65dd856826
